// @creaditor/page-kit — the single source of truth for programmatic
// creaditor landing-page construction.
//
// Consumed by BOTH:
//   - editor-api's MCP server (external Claude builds pages via tools), and
//   - cdtr-studio's landing-chat ability (studio's own AI builds pages).
//
// Both are just "brains" calling these deterministic "hands". Execution
// (persisting the tree) is NOT here — a consumer publishes the transactions
// onto the editor-api `edit:patch` Redis pipeline. `editPatch()` below builds
// the exact envelope that pipeline's consumer expects, so the wire contract is
// single-sourced too (see editor-api/src/app.js `edit:patch` subscriber).

const builder = require('./builder');
const { composeLandingSection, composeLandingNav, composeLandingFooter } = require('./landingSections');
const landingVocabulary = require('./landingVocabulary');
const SECTION_TEMPLATES = require('./sections.json');

// Every element type a page can contain: the tuned core content types plus the
// catalog widgets. Derived from the catalog data so it can never drift from it.
const ELEMENT_TYPES = [
  'heading', 'text', 'list', 'button', 'image', 'divider', 'spacer',
  ...Object.keys(builder.CATALOG_BODIES).sort(),
];

/**
 * Build the `edit:patch` message the editor-api pipeline consumes. A consumer
 * that has a Redis client applies a tree by:
 *   redis.publish('edit:patch', JSON.stringify(editPatch(siteId, userId, transactions)))
 * The consumer trusts { siteId, userId, transactions }; ids in `transactions`
 * are client-generated by the builder (cid), so no response is needed.
 */
const editPatch = (siteId, userId, transactions, transactionId) => ({
  siteId,
  userId,
  transactionId: transactionId || builder.cid().replace(/^cdtr-/, ''),
  transactions: Array.isArray(transactions) ? transactions : [transactions],
});

module.exports = {
  ...builder,
  composeLandingSection,
  composeLandingNav,
  composeLandingFooter,
  ...landingVocabulary,
  SECTION_TEMPLATES,
  ELEMENT_TYPES,
  editPatch,
};
